config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post'/login', to:'sessions#create'
  delete'/logout', to:'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :forums
  resources :messages
end

app/models/forum.rb
class Forum < ApplicationRecord
  belongs_to :user
  has_many :messages
  validates :user_id, presence: true
  validates :name, presence: true
  validates :title, presence: true, uniqueness: true

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def show
    @forum = Forum.find(params[:id])
    @messages = @forum.messages.paginate(page: params[:page])
    @message = current_user.messages.build
  end


  def index
    @forum = current_user.forums.build
    @forum_feed_items = Forum.all.paginate(page: params[:page]).order(updated_at: :desc)
  end

  def create
    @forum = current_user.forums.new(name: params[:name],title: params[:title])
    if params[:content].empty?
      flash[:danger] = ["Content can't be blank."]
    else
      if @forum.save
        flash[:success] = ["Forum created!"]
        @message = current_user.messages.new(name: params[:name],content: params[:content], forum_id: @forum.id)
        @message.save
      else
        @forum_feed_items = []
        flash[:danger] = @forum.errors.full_messages
      end
    end
    redirect_to forums_path
  end

  def destroy
  end


  def set_resent_message
    forum.messages.order(:created_at).first
  end

  private

  def forum_params
    params.require(:forum).permit(:title, :name)
  end
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/views/forums/_forum.html.erb
<li id="forum-<%= forum.id %>">
  <!-- <%= link_to gravatar_for(forum.user, size: 50), forum.user %> -->
  <span class="user"><%= link_to forum.title, forum_path(forum.id) %></span>
  <!-- <span class="content"><%= forum.name %></span> -->
  <span class="timestamp">
    Posted <%= time_ago_in_words(forum.created_at) %> ago.
    (<%= forum.messages.count %> 件)
    <%= forum.messages.order(:created_at).first.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M:%S') %>
  </span>
</li>

app/views/forums/index.html.erb
<% provide(:title, 'Forums') %>
<h1>Forums</h1>

<div class="row">
  <aside class="col-md-4">
    <section class="forum_form">
      <%= render 'shared/forum_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>スレッド一覧</h3>
    <%= render 'shared/forum_feed' %>
  </div>
</div>

app/views/forums/show.html.erb
<% provide(:title, @forum.title) %>
<div class="row">
  <h1>
    <%= @forum.title %>
  </h1>

  <aside class="col-md-4">
    <section class="message_form">
      <%= render 'shared/message_form' %>
    </section>
  </aside>
  <p>書き込み件数(<%= @messages.count %>)  </p>
  <div class="col-md-8">
    <% if @messages.any? %>
      <ol class="messages">
        <%= render @messages %>
      </ol>
      <%= will_paginate @messages %>
    <% end %>
  </div>

</div>